In [1]:
import pandas as pd

In [ ]:
C
print(s1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [19]:
s2=pd.Series([1,2,3,4,5]).index=(['a','d','f','c','r'])
print(s2.index)

<built-in method index of list object at 0x00000287BA9CFC40>

In [26]:
s3=pd.Series({'a': 10, 'b': 20, 'c': 30})
print(s3.values)

[10 20 30]

In [29]:
# Using a larger dataset
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    'Age': [25, 30, 35, 28, 25, 32],
    'Salary': [50000, 60000, 70000, 55000, 52000, 68000],
    'Department': ['HR', 'IT', 'IT', 'Finance', 'HR', 'IT'],
    'Experience': [2, 5, 8, 3, 2, 6]
})

# head() and tail()
print(df.head(2))
print(df.tail(2))

# unique() and nunique()
print(df['Department'].unique())
print(df['Department'].nunique())

# value_counts()
print(df['Department'].value_counts())
print(df['Age'].value_counts())

    Name  Age  Salary Department  Experience
0  Alice   25   50000         HR           2
1    Bob   30   60000         IT           5
    Name  Age  Salary Department  Experience
4    Eve   25   52000         HR           2
5  Frank   32   68000         IT           6
<StringArray>
['HR', 'IT', 'Finance']
Length: 3, dtype: str
3
Department
IT         3
HR         2
Finance    1
Name: count, dtype: int64
Age
25    2
30    1
35    1
28    1
32    1
Name: count, dtype: int64

In [32]:
import pandas as pd

data = {
"RollNo":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],

"Name":["Ali","Ahmed","Sara","Ayesha","Hassan","Usman","Fatima","Bilal","Hina","Zain",
       "Hamza","Noor","Iqra","Daniyal","Kiran","Saad","Maryam","Taha","Laiba","Farhan"],

"Age":[20,21,19,22,20,21,20,19,22,21,20,19,21,22,20,21,19,20,22,21],

"City":["GRW","GRW","GRW","GRW","GRW","GRW","GRW","GRW","GRW","GRW","GRW","GRW","GRW","GRW","GRW","GRW","GRW","GRW","GRW","GRW"],

"Gender":["Male","Male","Female","Female","Male","Male","Female","Male","Female","Male",
         "Male","Female","Female","Male","Female","Male","Female","Male","Female","Male"],

"Grade":["A","B","A","A","B","B","A","C","B","A","A","B","A","C","B","A","B","A","A","B"],

"Subject":["Math","CS","English","Physics","Math","CS","English","Physics","Math","CS",
          "English","Physics","Math","CS","English","Physics","Math","CS","English","Physics"],

"Total_Marks":[100]*20,

"Obtain_Marks":[90,85,88,92,80,75,89,70,84,91,86,78,90,72,83,88,79,94,87,81]
}

df = pd.DataFrame(data)

print(df)

    RollNo     Name  Age City  Gender Grade  Subject  Total_Marks  \
0        1      Ali   20  GRW    Male     A     Math          100
1        2    Ahmed   21  GRW    Male     B       CS          100
2        3     Sara   19  GRW  Female     A  English          100
3        4   Ayesha   22  GRW  Female     A  Physics          100
4        5   Hassan   20  GRW    Male     B     Math          100
5        6    Usman   21  GRW    Male     B       CS          100
6        7   Fatima   20  GRW  Female     A  English          100
7        8    Bilal   19  GRW    Male     C  Physics          100
8        9     Hina   22  GRW  Female     B     Math          100
9       10     Zain   21  GRW    Male     A       CS          100
10      11    Hamza   20  GRW    Male     A  English          100
11      12     Noor   19  GRW  Female     B  Physics          100
12      13     Iqra   21  GRW  Female     A     Math          100
13      14  Daniyal   22  GRW    Male     C       CS          100
14      15    Kiran   20  GRW  Female     B  English          100
15      16     Saad   21  GRW    Male     A  Physics          100
16      17   Maryam   19  GRW  Female     B     Math          100
17      18     Taha   20  GRW    Male     A       CS          100
18      19    Laiba   22  GRW  Female     A  English          100
19      20   Farhan   21  GRW    Male     B  Physics          100

    Obtain_Marks
0             90
1             85
2             88
3             92
4             80
5             75
6             89
7             70
8             84
9             91
10            86
11            78
12            90
13            72
14            83
15            88
16            79
17            94
18            87
19            81

In [14]:
import pandas as pd
df = pd.DataFrame({
    'Name':['Eman','Ayesha','Sana','Marym'],
    'Class':['BS','BS','BS','BS'],
    'Age':[19,20,19,20]
})
print(df)
print(df.info())
print(df.shape)

     Name Class  Age
0    Eman    BS   19
1  Ayesha    BS   20
2    Sana    BS   19
3   Marym    BS   20
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Class   4 non-null      str
 2   Age     4 non-null      int64
dtypes: int64(1), str(2)
memory usage: 228.0 bytes
None
(4, 3)

In [28]:
import pandas as pd
import numpy as np

In [22]:
df=pd.Series([1,2,3,4,5,6]).index=['a','b','c','d','e','f']
print(df.index)

<built-in method index of list object at 0x0000029706486B40>

In [ ]:
df=pd.DataFrame({                                     #dataframe form dictionary
    'Name':['hadia','Hunain','Asma'],
    'Age':[19,20,19],
    'City':['GRW','GRW','GRW']
})
print(df)

     Name  Age City
0   hadia   19  GRW
1  Hunain   20  GRW
2    Asma   19  GRW

In [33]:
#dataframe form list
df=pd.DataFrame([
    {'Name':'Eman', 'age':19,'city':'grw'},
    {'Name':'fatima', 'age':19, 'city':'grw'}
])



print(df)

     Name  age city
0    Eman   19  grw
1  fatima   19  grw

In [54]:
#dataframe form numpy
import pandas as pd
import numpy as np
df2 = pd.DataFrame(np.random.randn(4,3),
                columns=['A','B','C'],
                index=['row1','row2','row3','row4'])
print(df2)

             A         B         C
row1  0.979020 -0.350163  0.734137
row2  1.146088  0.629095  0.214111
row3 -0.327720  0.906244 -1.770316
row4 -0.714572  1.699691 -1.087225

In [55]:
df2.head(3)

             A         B         C
row1  0.979020 -0.350163  0.734137
row2  1.146088  0.629095  0.214111
row3 -0.327720  0.906244 -1.770316

In [56]:
df2.tail()

             A         B         C
row1  0.979020 -0.350163  0.734137
row2  1.146088  0.629095  0.214111
row3 -0.327720  0.906244 -1.770316
row4 -0.714572  1.699691 -1.087225

In [57]:
df2.groupby('A')['B'].mean()

A
-0.714572    1.699691
-0.327720    0.906244
 0.979020   -0.350163
 1.146088    0.629095
Name: B, dtype: float64

In [ ]:
# Using a larger dataset
df2 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    'Age': [25, 30, 35, 28, 25, 32],
    'Salary': [50000, 60000, 70000, 55000, 52000, 68000],
    'Department': ['HR', 'IT', 'IT', 'Finance', 'HR', 'IT'],
    'Experience': [2, 5, 8, 3, 2, 6]
})
pd.concat([df], ignore_index=True)
pd.concat([df],ignore_index=True,axis=0)

      Name  Age  Salary Department  Experience
0    Alice   25   50000         HR           2
1      Bob   30   60000         IT           5
2  Charlie   35   70000         IT           8
3    David   28   55000    Finance           3
4      Eve   25   52000         HR           2
5    Frank   32   68000         IT           6

In [62]:
pd.merge(df,df2, on='Name', how='left')

,Name,Age_x,Salary_x,Department_x,Experience_x,Age_y,Salary_y,Department_y,Experience_y
0,Alice,25,50000,HR,2,25,50000,HR,2
1,Bob,30,60000,IT,5,30,60000,IT,5
2,Charlie,35,70000,IT,8,35,70000,IT,8
3,David,28,55000,Finance,3,28,55000,Finance,3
4,Eve,25,52000,HR,2,25,52000,HR,2
5,Frank,32,68000,IT,6,32,68000,IT,6

In [70]:
import pandas as pd

In [81]:
df1=pd.read_csv(r'C:\Users\HP\Downloads\weather.csv')
df1

,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
0,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
1,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
2,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
3,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
4,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
5,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
6,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
7,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
8,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
9,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
10,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
11,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
12,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
13,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
14,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu
15,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
16,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
17,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
18,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
19,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
20,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
21,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
22,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
23,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
24,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
25,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
26,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
27,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
28,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
29,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
30,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   MIN temp (deg Celcius)  31 non-null     str
 1   Location                31 non-null     str
 2   Time                    31 non-null     str
 3   Wind                    31 non-null     str
 4   MAX temp (deg Celcius)  31 non-null     str
 5   Description             31 non-null     str
 6   Precipitation (in %)    31 non-null     str
 7   Date                    31 non-null     str
 8   Other Details           31 non-null     str
 9   Humidity (in %)         31 non-null     str
 10  Day                     31 non-null     str
dtypes: str(11)
memory usage: 2.8 KB

In [84]:
df1.columns

Index(['MIN temp (deg Celcius)', 'Location', 'Time', 'Wind',
       'MAX temp (deg Celcius)', 'Description', 'Precipitation (in %)', 'Date',
       'Other Details', 'Humidity (in %)', 'Day'],
      dtype='str')

In [94]:
df1.head()

,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
0,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
1,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
2,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
3,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
4,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon

In [95]:
df1.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16     True
17     True
18     True
19     True
20     True
21     True
22     True
23     True
24     True
25     True
26     True
27     True
28     True
29     True
30     True
dtype: bool

In [99]:
df1.drop(20)

,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
0,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
1,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
2,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
3,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
4,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
5,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
6,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
7,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
8,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
9,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
10,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
11,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
12,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
13,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
14,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu
15,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
16,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
17,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
18,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
19,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
21,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
22,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
23,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
24,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
25,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
26,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
27,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
28,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
29,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
30,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu

In [102]:
df1.shape

(31, 11)

In [103]:
df1.describe

<bound method NDFrame.describe of     MIN temp (deg Celcius)                       Location       Time  \
0                       22  Bharsul, India 10-day Weather  23:04 IST
1                       22  Bharsul, India 10-day Weather  23:04 IST
2                       22  Bharsul, India 10-day Weather  23:04 IST
3                       21  Bharsul, India 10-day Weather  23:04 IST
4                       21  Bharsul, India 10-day Weather  23:04 IST
5                       21  Bharsul, India 10-day Weather  23:04 IST
6                       21  Bharsul, India 10-day Weather  23:04 IST
7                       20  Bharsul, India 10-day Weather  23:04 IST
8                       20  Bharsul, India 10-day Weather  23:04 IST
9                       19  Bharsul, India 10-day Weather  23:04 IST
10                      19  Bharsul, India 10-day Weather  23:04 IST
11                      19  Bharsul, India 10-day Weather  23:04 IST
12                      19  Bharsul, India 10-day Weather  23:04 IST
13                      19  Bharsul, India 10-day Weather  23:04 IST
14                      19  Bharsul, India 10-day Weather  23:04 IST
15  MIN temp (deg Celcius)                       Location       Time
16                      22  Bharsul, India 10-day Weather  23:04 IST
17                      22  Bharsul, India 10-day Weather  23:04 IST
18                      22  Bharsul, India 10-day Weather  23:04 IST
19                      21  Bharsul, India 10-day Weather  23:04 IST
20                      21  Bharsul, India 10-day Weather  23:04 IST
21                      21  Bharsul, India 10-day Weather  23:04 IST
22                      21  Bharsul, India 10-day Weather  23:04 IST
23                      20  Bharsul, India 10-day Weather  23:04 IST
24                      20  Bharsul, India 10-day Weather  23:04 IST
25                      19  Bharsul, India 10-day Weather  23:04 IST
26                      19  Bharsul, India 10-day Weather  23:04 IST
27                      19  Bharsul, India 10-day Weather  23:04 IST
28                      19  Bharsul, India 10-day Weather  23:04 IST
29                      19  Bharsul, India 10-day Weather  23:04 IST
30                      19  Bharsul, India 10-day Weather  23:04 IST

           Wind  MAX temp (deg Celcius)   Description  Precipitation (in %)  \
0    NE 2 km/h                       --         Clear                     0
1   NNW 7 km/h                       36  Mostly Sunny                     0
2   SSW 5 km/h                       35         Sunny                     0
3   WSW 9 km/h                       36         Sunny                     0
4     N 9 km/h                       35         Sunny                     0
5     W 8 km/h                       35         Sunny                     0
6   SSE 7 km/h                       34  Mostly Sunny                     0
7   SSW 9 km/h                       34  Mostly Sunny                     0
8     E 7 km/h                       34  Mostly Sunny                     0
9   NE 10 km/h                       34         Sunny                     0
10   NE 7 km/h                       33         Sunny                     0
11  ENE 6 km/h                       33         Sunny                     0
12    E 6 km/h                       33         Sunny                     0
13  ESE 5 km/h                       33         Sunny                     0
14  NNW 5 km/h                       33         Sunny                     0
15         Wind  MAX temp (deg Celcius)   Description  Precipitation (in %)
16   NE 2 km/h                       --         Clear                     0
17  NNW 7 km/h                       36  Mostly Sunny                     0
18  SSW 5 km/h                       35         Sunny                     0
19  WSW 9 km/h                       36         Sunny                     0
20    N 9 km/h                       35         Sunny                     0
21    W 8 km/h                       35         Sunny                     0
22  SSE 7 km/h                       34  Mostly Sunny                     0
23  SSW 9 km/h                       34  Mostly Sunny                     0
24    E 7 km/h                       34  Mostly Sunny                     0
25  NE 10 km/h                       34         Sunny                     0
26   NE 7 km/h                       33         Sunny                     0
27  ENE 6 km/h                       33         Sunny                     0
28    E 6 km/h                       33         Sunny                     0
29  ESE 5 km/h                       33         Sunny                     0
30  NNW 5 km/h                       33         Sunny                     0

      Date                                      Other Details  \
0   18 OCT  Generally clear. Low 22ºC. Winds NE and variable.
1   19 OCT  Generally clear. High 36ºC. Winds NNW and vari...
2   20 OCT  Generally clear. High 35ºC. Winds SSW and vari...
3   21 OCT  Generally clear. High 36ºC. Winds WSW and vari...
4   22 OCT  Generally clear. High 35ºC. Winds N and variable.
5   23 OCT  Generally clear. High 35ºC. Winds W and variable.
6   24 OCT  Generally clear. High 34ºC. Winds SSE and vari...
7   25 OCT  Generally clear. High 34ºC. Winds SSW and vari...
8   26 OCT  Generally clear. High 34ºC. Winds E and variable.
9   27 OCT  Generally clear. High 34ºC. Winds NE at 10 to ...
10  28 OCT  Generally clear. High 33ºC. Winds NE and varia...
11  29 OCT  Generally clear. High 33ºC. Winds ENE and vari...
12  30 OCT  Generally clear. High 33ºC. Winds E and variable.
13  31 OCT  Generally clear. High 33ºC. Winds ESE and vari...
14   1 NOV  Generally clear. High 33ºC. Winds NNW and vari...
15    Date                                      Other Details
16  18 OCT  Generally clear. Low 22ºC. Winds NE and variable.
17  19 OCT  Generally clear. High 36ºC. Winds NNW and vari...
18  20 OCT  Generally clear. High 35ºC. Winds SSW and vari...
19  21 OCT  Generally clear. High 36ºC. Winds WSW and vari...
20  22 OCT  Generally clear. High 35ºC. Winds N and variable.
21  23 OCT  Generally clear. High 35ºC. Winds W and variable.
22  24 OCT  Generally clear. High 34ºC. Winds SSE and vari...
23  25 OCT  Generally clear. High 34ºC. Winds SSW and vari...
24  26 OCT  Generally clear. High 34ºC. Winds E and variable.
25  27 OCT  Generally clear. High 34ºC. Winds NE at 10 to ...
26  28 OCT  Generally clear. High 33ºC. Winds NE and varia...
27  29 OCT  Generally clear. High 33ºC. Winds ENE and vari...
28  30 OCT  Generally clear. High 33ºC. Winds E and variable.
29  31 OCT  Generally clear. High 33ºC. Winds ESE and vari...
30   1 NOV  Generally clear. High 33ºC. Winds NNW and vari...

    Humidity (in %)      Day
0                48  Tonight
1                29      Fri
2                29      Sat
3                32      Sun
4                31      Mon
5                29      Tue
6                28      Wed
7                27      Thu
8                29      Fri
9                30      Sat
10               28      Sun
11               26      Mon
12               27      Tue
13               27      Wed
14               28      Thu
15  Humidity (in %)      Day
16               48  Tonight
17               29      Fri
18               29      Sat
19               32      Sun
20               31      Mon
21               29      Tue
22               28      Wed
23               27      Thu
24               29      Fri
25               30      Sat
26               28      Sun
27               26      Mon
28               27      Tue
29               27      Wed
30               28      Thu  >

In [104]:
df1.Date

0     18 OCT
1     19 OCT
2     20 OCT
3     21 OCT
4     22 OCT
5     23 OCT
6     24 OCT
7     25 OCT
8     26 OCT
9     27 OCT
10    28 OCT
11    29 OCT
12    30 OCT
13    31 OCT
14     1 NOV
15      Date
16    18 OCT
17    19 OCT
18    20 OCT
19    21 OCT
20    22 OCT
21    23 OCT
22    24 OCT
23    25 OCT
24    26 OCT
25    27 OCT
26    28 OCT
27    29 OCT
28    30 OCT
29    31 OCT
30     1 NOV
Name: Date, dtype: str

In [109]:
df1.Time

0     23:04 IST
1     23:04 IST
2     23:04 IST
3     23:04 IST
4     23:04 IST
5     23:04 IST
6     23:04 IST
7     23:04 IST
8     23:04 IST
9     23:04 IST
10    23:04 IST
11    23:04 IST
12    23:04 IST
13    23:04 IST
14    23:04 IST
15         Time
16    23:04 IST
17    23:04 IST
18    23:04 IST
19    23:04 IST
20    23:04 IST
21    23:04 IST
22    23:04 IST
23    23:04 IST
24    23:04 IST
25    23:04 IST
26    23:04 IST
27    23:04 IST
28    23:04 IST
29    23:04 IST
30    23:04 IST
Name: Time, dtype: str

In [120]:
df1.isnull()

,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df1.index

In [1]:
import pandas as pd

In [2]:
df2=pd.DataFrame({'A':[1,2,3,4,5],'B':[10,20,30,40,50]})
df2

   A   B
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50

In [ ]:
df3=pd.DataFrame({'A':[6,7,8,9,10],'B':[60,70,80,90,100]})
df3

   A   B
0  6  60
1  7  70
2  8  80

In [5]:
display(df2,df3)

   A   B
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50

   A   B
0  6  60
1  7  70
2  8  80

In [ ]:
df3.append(df2)

AttributeError: 'DataFrame' object has no attribute 'append'

In [ ]:
df2.append(df3,ignore_index=True)